In [10]:
import matplotlib.pyplot as plt
import pandas as pd
import os
%matplotlib inline

plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
def save_fig(fig_name, tight_layout=True):
    path = os.path.join('Figures', fig_name + '.png')
    print('Saving figure', fig_name)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

df = pd.read_csv('../binary/X.csv', header=None)
y = pd.read_csv('../binary/y.csv', header=None)
df['y'] = y

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Columns: 922 entries, 0 to y
dtypes: float64(921), int64(1)
memory usage: 1.3 MB

In [12]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,912,913,914,915,916,917,918,919,920,y
count,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,...,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,-7.285778,26.623167,-39.141444,31.432056,19.583389,-27.309889,-1.363278,16.758222,-1.462556,20.104333,...,-0.391444,6.723667,-10.397389,6.965833,-17.164222,2.614111,-0.534778,7.659167,27.403722,0.500000
std,28.066784,38.301483,38.125418,16.871401,19.078221,25.123531,28.830671,24.518862,24.424941,22.169355,...,27.783458,32.377364,34.395392,35.424993,42.765649,33.565696,30.336068,23.692330,20.522360,0.501395
min,-74.140000,-92.590000,-143.410000,-13.050000,-25.910000,-87.240000,-72.790000,-64.190000,-79.430000,-44.400000,...,-45.670000,-50.880000,-70.100000,-64.090000,-92.670000,-59.460000,-55.220000,-37.350000,-12.100000,0.000000
25%,-24.740000,2.035000,-63.590000,19.257500,6.325000,-41.460000,-20.357500,2.350000,-15.630000,5.200000,...,-24.952500,-23.310000,-44.620000,-25.830000,-59.050000,-26.330000,-27.592500,-13.342500,8.255000,0.000000
50%,-8.725000,28.960000,-35.035000,31.315000,18.445000,-27.265000,-1.695000,16.980000,0.300000,19.925000,...,-5.640000,4.385000,-10.635000,5.745000,-18.400000,-2.005000,0.430000,8.120000,29.080000,0.500000
75%,11.212500,52.927500,-12.890000,44.292500,34.950000,-8.497500,19.560000,35.207500,14.840000,33.822500,...,25.162500,36.692500,21.817500,39.475000,20.445000,32.507500,26.692500,29.067500,45.830000,1.000000
max,71.960000,145.480000,58.810000,72.410000,66.890000,47.220000,82.840000,79.350000,71.910000,75.150000,...,48.820000,66.170000,57.770000,71.210000,56.550000,68.440000,62.360000,47.640000,65.770000,1.000000

In [13]:
corr_matrix = df.corr()
corr_matrix["y"].sort_values(ascending=False)

y      1.000000
601    0.996882
602    0.996760
639    0.996681
680    0.996675
596    0.996674
627    0.996612
650    0.996604
613    0.996576
592    0.996551
641    0.996550
618    0.996542
615    0.996515
637    0.996507
671    0.996495
574    0.996490
609    0.996465
644    0.996462
595    0.996443
586    0.996422
584    0.996411
610    0.996399
582    0.996375
651    0.996373
628    0.996369
625    0.996368
649    0.996355
631    0.996354
634    0.996336
676    0.996335
         ...
287   -0.994738
324   -0.994759
365   -0.994761
354   -0.994771
346   -0.994782
340   -0.994791
339   -0.994807
370   -0.994821
327   -0.994829
304   -0.994832
345   -0.994833
361   -0.994854
348   -0.994855
341   -0.994875
357   -0.994896
344   -0.994909
367   -0.994920
302   -0.994957
329   -0.994966
318   -0.994970
306   -0.994997
356   -0.995009
351   -0.995011
296   -0.995035
377   -0.995038
336   -0.995080
305   -0.995087
371   -0.995088
301   -0.995159
331   -0.995165
Name: y, Length: 922, dtype: float64